dist: trusty
language: node_js
node_js: "6"

addons:
  sonarqube:
    branches:
      - .*

install:
  - npm install

script:
  - sonar-scanner -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.branch=$TRAVIS_BRANCH -Dsonar.sources=src/ -Dsonar.projectKey=de.hpi.bpt:argos-frontend -Dsonar.projectName=argos-frontend -Dsonar.projectVersion=1.0
  - npm test
  - npm build

notifications:
  email: false