dist: trusty
language: node_js
node_js: "6"

addons:
  sonarqube:
    branches:
      - .*

install:
  - npm install

script:
  - sonar-scanner -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.branch=$TRAVIS_BRANCH
  - npm test
  - npm build

notifications:
  email: false